
image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  custom:
    deploy:
        - step:
            name: Build and Test
            runs-on: homelab
            script:
              - docker-compose up --build -d 